# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Send to Firebase App Distribution"
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  lane :distribute do
    firebase_app_distribution(
      app: "1:919475980218:android:4bc391401a637fc0947f83",
      testers: "yukuku@gmail.com",
      apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end
end
