name: grii_resmi
version: 0.3.0+30

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^2.2.1
  firebase_core: ^1.6.0
  flutter_search_bar: ^3.0.0-dev.1
  flutter_widget_from_html_core: ^0.6.2
  flutter_linkify: ^5.0.2
  http: ^0.13.3
  intl: ^0.17.0
  just_audio: ^0.9.10
  package_info: ^2.0.2
  path_provider: ^2.0.3
  shared_preferences: ^2.0.7
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.10
  uuid: ^3.0.4

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/drawable/ic_launcher.png
    - assets/KRI/
    - assets/KPRI/
    - assets/JB/
    - assets/cabang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
