name: grii_resmi

dependencies:
  flutter:
    sdk: flutter
  simple_audio_player:
    path: ../simple_audio_player/
  flutter_search_bar:
  http: ^0.12.1
  path_provider: ^1.6.10
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.1
  timeline_tile: ^0.1.2
  flutter_linkify: ^3.1.3
  url_launcher: ^5.4.10
  firebase_crashlytics: ^0.1.3+3
  uuid: 2.1.0
  flutter_widget_from_html_core: ^0.4.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/drawable/ic_launcher.png
    - assets/KRI/
    - assets/KPRI/
    - assets/JB/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
